#!/bin/bash
# echo -n 'Enter dimensions of matA : '
read ax ay
declare -A A
for ((i=0; i<ax; ++i)); do
	declare -a x
	read -a x
	if ((${#x[*]}!=ay)); then
		echo 'Input miss match'
		exit
	fi
	A[$i]=${x[*]}
done
# echo -n 'Enter dimensions of matB : '
read bx by
if [ $ax -ne $bx ] || [ $ay -ne $by ]; then
	echo 'Cannot add mats'
	exit
fi
declare -A B
for ((i=0; i<bx; ++i)); do
	read -a x
	if ((${#x[*]}!=by)); then
		echo 'Input miss match'
		exit
	fi
	B[$i]=${x[*]}
done
declare -A C
for ((i=0; i<bx; ++i)); do
	for c1 in ${A[$i]}; do
		echo $c
	done
done
