#!/bin/bash
echo -n 'Enter dimensions of matA : '
read ax ay
declare -A A
for ((i=0; i<ax; ++i)); do
	read -a arr
	for ((j=0; j<ay; ++j)); do
		A[$i,$j]=${arr[$j]}
	done
done
echo -n 'Enter dimensions of matB : '
read bx by
if [ $ax -ne $bx ] || [ $ay -ne $by ]; then
	echo 'Cannot add mats'
	exit
fi
for ((i=0; i<bx; ++i)); do
	read -a arr
	for ((j=0; j<by; ++j)); do
		((A[$i,$j] += arr[j]))
	done
done
echo -e '\nSum\n'
for ((i=0; i<bx; ++i)); do
	for ((j=0; j<by; ++j)); do
		printf "%-5d" ${A[$i,$j]}
	done
	echo
done