#!/bin/bash
if test $# -lt 1; then
	echo "Usage: $0 string"
	exit
fi
str=$1
len=${#str}
msg="Palindrome"
for ((i=0,j=len-1; i<len/2; ++i, --j)); do
	if [ ${str:$i:1} != ${str:$j:1} ]; then
		msg="Not palindrome"
		break
	fi
done
echo $msg