#!/bin/bash
if test $# -lt 1; then
	echo 'Usage: ./7 string'
	exit
fi
len=${#1}
str=$1
msg="Palindrome"
for ((i=0,j=len-1; i<len/2; ++i, --j)); do
	# if (( ${1:$i:1} != ${1:$j:1} )); then
	if (( ${str:i:1} != ${str:j:1} )); then
		msg="Not palindrome"
		break
	fi
done
echo $msg