#!/bin/bash
echo "Enter 10 elements"
((n=p=z=0))
for (( i=0; i<10; ++i )); do
	read arr[i]
	if ((arr[i]>0)); then
		((p++))
	elif ((arr[i]<0)); then
		((n++))
	else
		((z++))
	fi
done
for (( i=0; i<10-1; ++i )); do
	for (( j=0; j<10-i-1; ++j)); do
		if ((arr[j]>arr[j+1])); then
			((t=arr[j]))
			((arr[j]=arr[j+1]))
			((arr[j+1]=t))
		fi
	done
done 
echo -e "Zero :" $z "\n+ve  :" $p "\n-ve  :" $n
echo ${arr[*]}