#!/bin/bash
echo 'Enter 10 elements'
((n=p=z=0))
str=''
for (( i=0; i<10; ++i )); do
	read x
	if ((x>0)); then
		((p++))
	elif ((x<0)); then
		((n++))
	else
		((z++))
	fi
	str+=$x
	str+=' '
done
echo -e 'Zero :' $z '\n+ve  :' $p '\n-ve  :' $n
echo $(echo $str | tr ' ' '\n' | sort -n)
