#!/bin/bash
((fc=dc=0))
for x in `ls`; do 
	if [ -f $x ]; then
		fa[$fc]=$x
		((fc++))
	elif [ -d $x ]; then
		da[$dc]=$x
		((dc++))
	fi
done
echo -e '#Files :' $fc '\n#Directories :' $dc
echo -e 'Files :' ${fa[*]} '\nDirectories :' ${da[*]}